name: .NET

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/pwXt-cli/pwXt-cli.csproj
    - name: Build
      run: dotnet build --no-restore ./src/pwXt-cli/pwXt-cli.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./tests/pwXt-cli.Tests/pwXt-cli.Tests.csproj
